Added permissions-contents-write to scrape_talks.yml

diff --git a/.github/workflows/scrape_talks.yml b/.github/workflows/scrape_talks.yml
--- a/.github/workflows/scrape_talks.yml
+++ b/.github/workflows/scrape_talks.yml
@@ -7,6 +7,9 @@ on:
       - '_talks/**'
       - 'talkmap.ipynb'
 
+permissions: # Chatgpt told me to add because action bot was failing...
+  contents: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -28,10 +31,10 @@ jobs:
       run: |
         jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb
 
-    # - name: Commit changes
-    #   run: |
-    #     git config user.name "github-actions[bot]"
-    #     git config user.email "github-actions[bot]@users.noreply.github.com"
-    #     git add .
-    #     git commit -m "Automated update of talk locations" || echo "No changes to commit"
-    #     git push
+    - name: Commit changes
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git add .
+        git commit -m "Automated update of talk locations" || echo "No changes to commit"
+        git push
